name: '✨ Feature Request'
description: 'Suggest a new feature or improvement for a project.'
title: '[FEATURE] '
labels: ['enhancement']
assignees: []

body:
  - type: markdown
    content: |
      **Describe the feature**
      A clear and concise description of what you want to happen.

  - type: input
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Why is this feature needed?
      placeholder: 'This feature is useful because ...'
      required: true

  - type: input
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on implementation, describe them
      placeholder: 'Consider adding a new endpoint / UI element ...'
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any extra context, screenshots, mockups, or links.
      placeholder: 'Wireframes, designs, references ...'
      required: false
